/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pacbio_IceCreamAlignerJNI */

#ifndef _Included_pacbio_IceCreamAlignerJNI
#define _Included_pacbio_IceCreamAlignerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pacbio_IceCreamAlignerJNI
 * Method:    alignForwardJNI
 * Signature: ([I[I[IIIIF)V
 */
JNIEXPORT void JNICALL Java_pacbio_IceCreamAlignerJNI_alignForwardJNI
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jint, jint, jint, jfloat);

/*
 * Class:     pacbio_IceCreamAlignerJNI
 * Method:    alignForward16JNI
 * Signature: ([S[S[ISSSF)V
 */
JNIEXPORT void JNICALL Java_pacbio_IceCreamAlignerJNI_alignForward16JNI
  (JNIEnv *, jclass, jshortArray, jshortArray, jintArray, jshort, jshort, jshort, jfloat);

/*
 * Class:     pacbio_IceCreamAlignerJNI
 * Method:    alignForwardShortJNI
 * Signature: ([I[I[III)V
 */
JNIEXPORT void JNICALL Java_pacbio_IceCreamAlignerJNI_alignForwardShortJNI
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     pacbio_IceCreamAlignerJNI
 * Method:    alignForwardShort16JNI
 * Signature: ([S[S[ISS)V
 */
JNIEXPORT void JNICALL Java_pacbio_IceCreamAlignerJNI_alignForwardShort16JNI
  (JNIEnv *, jclass, jshortArray, jshortArray, jintArray, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
